'use client';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarInset,
  SidebarFooter,
  SidebarSeparator,
} from '@/components/ui/sidebar';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import {
  Home,
  BarChart3,
  Package,
  ShoppingCart,
  ClipboardList,
  BrainCircuit,
  GitCompareArrows,
  Users,
  LogOut,
  FolderArchive,
} from 'lucide-react';

const navLinks = [
  { href: '/', label: 'Analizador CSV', icon: Home },
  { href: '/historical-analysis', label: 'Módulos Históricos', icon: FolderArchive },
  { href: '/historical-analysis/sales', label: 'Análisis de Ventas', icon: BarChart3 },
  { href: '/historical-analysis/inventory', label: 'Análisis de Inventario', icon: Package },
  { href: '/historical-analysis/operations', label: 'Análisis de Adquisiciones', icon: ShoppingCart },
  { href: '/historical-analysis/products', label: 'Análisis de Publicaciones', icon: ClipboardList },
  { href: '/historical-analysis/trends-prediction', label: 'Predicción de Tendencias', icon: BrainCircuit },
  { href: '/historical-analysis/major-minor-sales', label: 'Ventas por Mayor y Menor', icon: GitCompareArrows },
  { href: '/historical-analysis/access-management', label: 'Gestión de Accesos', icon: Users },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="es">
      <head>
        <title>Firebase Studio App</title>
        <meta name="description" content="Generated by Firebase Studio" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <SidebarProvider>
          <Sidebar>
            <SidebarContent>
              <SidebarMenu>
                {navLinks.map((link) => (
                  <SidebarMenuItem key={link.href}>
                    <Link href={link.href} passHref legacyBehavior>
                      <SidebarMenuButton
                        isActive={pathname === link.href}
                        tooltip={{ children: link.label, side: 'right', align: 'center' }}
                      >
                        <link.icon />
                        <span>{link.label}</span>
                      </SidebarMenuButton>
                    </Link>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarContent>
            <SidebarFooter>
              <SidebarSeparator />
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton tooltip={{ children: 'Cerrar Sesión', side: 'right', align: 'center' }}>
                    <LogOut />
                    <span>Cerrar Sesión</span>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>
            {children}
          </SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
