'use client';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarInset,
  SidebarFooter,
  SidebarSeparator,
  SidebarHeader,
} from '@/components/ui/sidebar';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import {
  BarChart3,
  Receipt,
  GitCompareArrows,
  Repeat,
  FileCheck,
  AlertTriangle,
  Users,
  Landmark,
  LogOut,
  Flame,
  Puzzle,
  ClipboardList,
} from 'lucide-react';

const menuLinks = [
  { href: '/', label: 'Analizador de datos CSV', icon: FileCheck },
  { href: '/historical-analysis/sales', label: 'Ventas', icon: BarChart3 },
  { href: '/historical-analysis/operations', label: 'Gastos diarios', icon: Receipt },
  { href: '/historical-analysis/major-minor-sales', label: 'Consumo (ventas + Siggo)', icon: GitCompareArrows },
  { href: '/historical-analysis/trends-prediction', label: 'Recompra', icon: Repeat },
  { href: '/historical-analysis/publications', label: 'Análisis de Publicaciones', icon: ClipboardList },
  { href: '/historical-analysis/mapping-reconciliation', label: 'Mapeo y conciliación', icon: Puzzle },
  { href: '/historical-analysis/alerts', label: 'Alertas', icon: AlertTriangle },
  { href: '/historical-analysis/access-management', label: 'Auditoría', icon: Users },
  { href: '/historical-analysis/financial-close', label: 'Cierre financiero', icon: Landmark },
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="es">
      <head>
        <title>Firebase Studio App</title>
        <meta name="description" content="Generated by Firebase Studio" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <SidebarProvider>
          <Sidebar>
            <SidebarHeader>
              <div className="flex items-center gap-2.5 px-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                  <Flame className="h-5 w-5" />
                </div>
                <span className="text-lg font-semibold tracking-tight">Análisis Pro</span>
              </div>
            </SidebarHeader>
            <SidebarContent className="p-2">
              <SidebarMenu>
                {menuLinks.map((link) => (
                  <SidebarMenuItem key={link.href}>
                    <SidebarMenuButton
                      asChild
                      isActive={pathname === link.href || (link.href !== '/' && pathname.startsWith(link.href))}
                      tooltip={{ children: link.label, side: 'right', align: 'center' }}
                    >
                      <Link href={link.href}>
                        <link.icon />
                        <span>{link.label}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarContent>
            <SidebarFooter>
              <SidebarSeparator />
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton tooltip={{ children: 'Cerrar Sesión', side: 'right', align: 'center' }}>
                    <LogOut />
                    <span>Cerrar Sesión</span>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>{children}</SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
