'use client';
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import {
  SidebarProvider,
  Sidebar,
  SidebarContent,
  SidebarMenu,
  SidebarMenuItem,
  SidebarMenuButton,
  SidebarInset,
  SidebarFooter,
  SidebarSeparator,
  SidebarHeader,
} from '@/components/ui/sidebar';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import {
  Home,
  BarChart3,
  ShoppingCart,
  BrainCircuit,
  GitCompareArrows,
  Users,
  LogOut,
  FolderArchive,
  Flame,
} from 'lucide-react';

const mainLinks = [{ href: '/', label: 'Analizador CSV', icon: Home }];

const analysisLinks = [
  { href: '/historical-analysis', label: 'Resumen', icon: FolderArchive },
  { href: '/historical-analysis/sales', label: 'Análisis de Ventas', icon: BarChart3 },
  { href: '/historical-analysis/operations', label: 'Análisis de Adquisiciones', icon: ShoppingCart },
  { href: '/historical-analysis/trends-prediction', label: 'Predicción de Tendencias', icon: BrainCircuit },
  { href: '/historical-analysis/major-minor-sales', label: 'Ventas por Mayor y Menor', icon: GitCompareArrows },
  { href: '/historical-analysis/access-management', label: 'Gestión de Accesos', icon: Users },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  return (
    <html lang="es">
      <head>
        <title>Firebase Studio App</title>
        <meta name="description" content="Generated by Firebase Studio" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <SidebarProvider>
          <Sidebar>
            <SidebarHeader>
              <div className="flex items-center gap-2.5 px-2">
                <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                  <Flame className="h-5 w-5" />
                </div>
                <span className="text-lg font-semibold tracking-tight">Análisis Pro</span>
              </div>
            </SidebarHeader>
            <SidebarContent className="p-2">
              <SidebarMenu>
                {mainLinks.map((link) => (
                  <SidebarMenuItem key={link.href}>
                    <SidebarMenuButton
                      asChild
                      isActive={pathname === link.href}
                      tooltip={{ children: link.label, side: 'right', align: 'center' }}
                    >
                      <Link href={link.href}>
                        <link.icon />
                        <span>{link.label}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
              <SidebarSeparator className="my-2" />
              <div className="px-2 py-1">
                <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground/80">
                  Módulos de Análisis
                </span>
              </div>
              <SidebarMenu>
                {analysisLinks.map((link) => (
                  <SidebarMenuItem key={link.href}>
                    <SidebarMenuButton
                      asChild
                      isActive={pathname.startsWith(link.href)}
                      tooltip={{ children: link.label, side: 'right', align: 'center' }}
                    >
                      <Link href={link.href}>
                        <link.icon />
                        <span>{link.label}</span>
                      </Link>
                    </SidebarMenuButton>
                  </SidebarMenuItem>
                ))}
              </SidebarMenu>
            </SidebarContent>
            <SidebarFooter>
              <SidebarSeparator />
              <SidebarMenu>
                <SidebarMenuItem>
                  <SidebarMenuButton tooltip={{ children: 'Cerrar Sesión', side: 'right', align: 'center' }}>
                    <LogOut />
                    <span>Cerrar Sesión</span>
                  </SidebarMenuButton>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>{children}</SidebarInset>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
